CREATE TABLE [dbo].[中转仓] (
    [ID]   UNIQUEIDENTIFIER NOT NULL,
    [Name] NVARCHAR (50)    NOT NULL,
    [SN]   INT              NOT NULL,
    CONSTRAINT [PK_中转仓] PRIMARY KEY CLUSTERED ([ID] ASC)
);

